### ISSUE TITLE
Help with scaling the height of a UIView

### ISSUE THREAD

**Issue by jimbojsb** [miklselsoe/MSSPopMasonry#2]
Hi, I was wondering if you could provide guidance here:

Given a subclass of UIView with constraints:
```objc
    [self makeConstraints:^(MASConstraintMaker *make) {
        self.heightConstraint = make.height.equalTo(@36);
    }];
```

How would I animate the height to ```@400```? I tried combinations of ```NSValue``` and ```CGSize``` without much luck.

**Comment by jlehman** [comment]
You don't animate the height value itself, rather you animate the offset appended to the height value. Right now your offset is zero as you haven't set it to anything (which is perfectly acceptable).

Here's an example:

POPSpringAnimation *slideTo = [POPSpringAnimation new];
slideTo.toValue = @(400);
slideTo.springBounciness = 6;
slideTo.springSpeed = 25;
slideTo.property = [POPAnimatableProperty mas_offsetProperty];
[self.heightConstraint pop_addAnimation:slideTo forKey:@"PopSlideToAnimation"];

**Comment by jimbojsb** [comment]
You sir, are a gentleman and a scholar. That works perfectly.

**Comment by jlehman** [comment]
Glad to help!
