### ISSUE TITLE
ssh_askpass: exec(/usr/libexec/ssh-askpass): No such file or directory

### ISSUE THREAD

**Issue by sadiq81** [miklselsoe/MSSPopMasonry#3]
I get this stack trace when trying to install via cocoa pods

[!] Error installing MSSPopMasonry
[!] /usr/bin/git clone git@github.com:miklselsoe/MSSPopMasonry.git /Users/privat/iOS/HalalGuide/Pods/MSSPopMasonry --single-branch --depth 1 --branch 0.0.1

Cloning into '/Users/privat/iOS/HalalGuide/Pods/MSSPopMasonry'...

ssh_askpass: exec(/usr/libexec/ssh-askpass): No such file or directory

Host key verification failed.

fatal: Could not read from remote repository.

Please make sure you have the correct access rights

and the repository exists.
Failed with exit code: 1

**Comment by miklselsoe** [comment]
Not sure why you see this. It may have been a server glitch. If you try again now, is it still a problem?

**Comment by sadiq81** [comment]
No i'm still getting it.

I'll try investing again if it is something on my end.


Med venlig hilsen / Best regards

Tommy Sadiq Hinrichsen
Software Pilot

Humlebækgade 16, 1.tv.
2200 København N
Tlf: 26 24 14 36

Mangler du en billig anlægsgartner, så prøv http://www.sl-haveanlaeg.dk

2015-03-24 7:47 GMT+01:00 Mikkel Selsøe Sørensen <notifications@github.com>:

**Comment by xinwo** [comment]
same problem here

**Comment by xinwo** [comment]
pod update is ok
pod install has the problem

**Comment by miklselsoe** [comment]
I am more or less clueless about this problem. I haven't ever seen this. However googling it bit, I found this:
https://github.com/markcarver/mac-ssh-askpass

I hope it solves it for you. Please report back how it works out.

**Comment by sadiq81** [comment]
I finally solved it, something must have gone wrong with my SSH key to github.

Followed this guide https://help.github.com/articles/generating-ssh-keys/

Sry to have bothered you.

**Comment by HemingNM** [comment]
Solved!
Just saved "ssh-askpass" (downloaded from "https://github.com/markcarver/mac-ssh-askpass") to “/usr/X11R6/bin/“.
